# Generated by Django 4.2.7 on 2023-11-20 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_foodgram', '0003_alter_recipe_cooking_time_alter_recipe_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Мин. время - 1 минута')], verbose_name='Время приготовления'),
        ),
    ]
